//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sic.Apollo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleFor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleFor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sic.Apollo.Resources.TitleFor", typeof(TitleFor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        public static string EpicrisisPatientFiles {
            get {
                return ResourceManager.GetString("EpicrisisPatientFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evoluciones.
        /// </summary>
        public static string EpicrisisPatientMedicalCares {
            get {
                return ResourceManager.GetString("EpicrisisPatientMedicalCares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedentes.
        /// </summary>
        public static string EpicrisisPatientMedicalHistories {
            get {
                return ResourceManager.GetString("EpicrisisPatientMedicalHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen Físico.
        /// </summary>
        public static string EpicrisisPatientPhysicalExamination {
            get {
                return ResourceManager.GetString("EpicrisisPatientPhysicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string EpicrisisPatientProfile {
            get {
                return ResourceManager.GetString("EpicrisisPatientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string EpicrisisPatientResume {
            get {
                return ResourceManager.GetString("EpicrisisPatientResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signos Vitales.
        /// </summary>
        public static string EpicrisisPatientVitalSigns {
            get {
                return ResourceManager.GetString("EpicrisisPatientVitalSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial.
        /// </summary>
        public static string EpicrisisVitalSignHistory {
            get {
                return ResourceManager.GetString("EpicrisisVitalSignHistory", resourceCulture);
            }
        }
    }
}
